<?php
declare(strict_types=1);
namespace App\Modules\Payments;
use App\Core\Database\Database;
use DomainException;
use PDO;
final class WithdrawalPolicyService {
 public function rules(): array { $r=Database::connection()->query('SELECT * FROM withdrawal_rules WHERE id=1')->fetch() ?: []; return $this->map($r); }
 public function save(array $in): array { $v=['enabled'=>!empty($in['enabled'])?1:0,'min'=>(int)($in['min_withdrawal_minor']??0),'max'=>$this->nullable($in['max_withdrawal_minor']??null),'daily'=>$this->nullable($in['daily_limit_minor']??null),'count'=>$this->nullable($in['max_requests_per_day']??null),'req'=>!empty($in['require_paid_deposit'])?1:0,'dep'=>(int)($in['min_paid_deposit_minor']??0),'cool'=>(int)($in['cooldown_after_identity_change_hours']??0)]; if($v['min']<0||($v['max']!==null&&$v['max']<$v['min'])) throw new DomainException('Limites de saque inválidos.'); $s=Database::connection()->prepare('UPDATE withdrawal_rules SET enabled=:enabled,min_withdrawal_minor=:min,max_withdrawal_minor=:max,daily_limit_minor=:daily,max_requests_per_day=:count,require_paid_deposit=:req,min_paid_deposit_minor=:dep,cooldown_after_identity_change_hours=:cool WHERE id=1');$s->execute($v);return $this->rules(); }
 public function assertAllowed(PDO $pdo,string $userId,int $amount): void { $s=$pdo->query('SELECT * FROM withdrawal_rules WHERE id=1 FOR UPDATE');$r=$s->fetch();if(!$r||!(bool)$r['enabled'])throw new DomainException('Saques estão temporariamente indisponíveis.');$min=(int)$r['min_withdrawal_minor'];$max=$r['max_withdrawal_minor']===null?null:(int)$r['max_withdrawal_minor'];if($amount<$min)throw new DomainException('O valor está abaixo do mínimo global de saque.');if($max!==null&&$amount>$max)throw new DomainException('O valor excede o máximo global de saque.');$q=$pdo->prepare("SELECT COUNT(*) c,COALESCE(SUM(amount_minor),0) total FROM payment_transactions WHERE user_id=:u AND kind='WITHDRAWAL' AND status NOT IN ('CANCELLED','FAILED') AND created_at>=CURDATE()");$q->execute(['u'=>$userId]);$d=$q->fetch();if($r['max_requests_per_day']!==null&&(int)$d['c']>=(int)$r['max_requests_per_day'])throw new DomainException('Limite diário de solicitações de saque atingido.');if($r['daily_limit_minor']!==null&&((int)$d['total']+$amount)>(int)$r['daily_limit_minor'])throw new DomainException('Limite diário de valor para saques excedido.');if((bool)$r['require_paid_deposit']){$q=$pdo->prepare("SELECT COALESCE(SUM(amount_minor),0) total FROM payment_transactions WHERE user_id=:u AND kind='DEPOSIT' AND status='PAID'");$q->execute(['u'=>$userId]);if((int)$q->fetchColumn()<(int)$r['min_paid_deposit_minor'])throw new DomainException('É necessário possuir depósito pago antes de solicitar saque.');}$cool=(int)$r['cooldown_after_identity_change_hours'];if($cool>0){$q=$pdo->prepare('SELECT updated_at,created_at FROM users WHERE id=:u');$q->execute(['u'=>$userId]);$u=$q->fetch();if($u&&$u['updated_at']!==$u['created_at']&&strtotime((string)$u['updated_at'])>time()-($cool*3600))throw new DomainException("Saque temporariamente bloqueado após alteração cadastral. Aguarde {$cool} hora(s).");}}
 private function nullable(mixed $v): ?int {return $v===null||$v===''?null:max(0,(int)$v);} private function map(array $r):array{return ['enabled'=>(bool)($r['enabled']??0),'min_withdrawal_minor'=>(int)($r['min_withdrawal_minor']??0),'max_withdrawal_minor'=>isset($r['max_withdrawal_minor'])?(int)$r['max_withdrawal_minor']:null,'daily_limit_minor'=>isset($r['daily_limit_minor'])?(int)$r['daily_limit_minor']:null,'max_requests_per_day'=>isset($r['max_requests_per_day'])?(int)$r['max_requests_per_day']:null,'require_paid_deposit'=>(bool)($r['require_paid_deposit']??0),'min_paid_deposit_minor'=>(int)($r['min_paid_deposit_minor']??0),'cooldown_after_identity_change_hours'=>(int)($r['cooldown_after_identity_change_hours']??0)];}
}
