CREATE TABLE IF NOT EXISTS casino_providers (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 code VARCHAR(60) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL,
 enabled TINYINT(1) NOT NULL DEFAULT 0,
 mode ENUM('DEMO','PRODUCTION') NOT NULL DEFAULT 'DEMO',
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS casino_games (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 provider_id BIGINT UNSIGNED NOT NULL,
 external_id VARCHAR(190) NOT NULL,
 name VARCHAR(190) NOT NULL,
 category ENUM('SLOTS','LIVE','TABLE','OTHER') NOT NULL DEFAULT 'SLOTS',
 image_url VARCHAR(500) NULL,
 enabled TINYINT(1) NOT NULL DEFAULT 0,
 featured TINYINT(1) NOT NULL DEFAULT 0,
 sort_order INT NOT NULL DEFAULT 100,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
 UNIQUE KEY uq_casino_game_external (provider_id,external_id),
 INDEX idx_casino_public (enabled,featured,sort_order),
 CONSTRAINT fk_casino_game_provider FOREIGN KEY (provider_id) REFERENCES casino_providers(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
