CREATE TABLE IF NOT EXISTS casino_api_credentials (
 id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
 integration_code VARCHAR(60) NOT NULL UNIQUE,
 base_url VARCHAR(255) NOT NULL,
 credentials_encrypted LONGTEXT NOT NULL,
 enabled TINYINT(1) NOT NULL DEFAULT 0,
 created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
 updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
