CREATE TABLE withdrawal_rules (
 id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
 enabled TINYINT(1) NOT NULL DEFAULT 1,
 min_withdrawal_minor BIGINT UNSIGNED NOT NULL DEFAULT 1000,
 max_withdrawal_minor BIGINT UNSIGNED NULL DEFAULT 500000,
 daily_limit_minor BIGINT UNSIGNED NULL DEFAULT 1000000,
 max_requests_per_day INT UNSIGNED NULL DEFAULT 3,
 require_paid_deposit TINYINT(1) NOT NULL DEFAULT 1,
 min_paid_deposit_minor BIGINT UNSIGNED NOT NULL DEFAULT 1000,
 cooldown_after_identity_change_hours INT UNSIGNED NOT NULL DEFAULT 24,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO withdrawal_rules (id) VALUES (1);
